### ISSUE TITLE
concat changes forward slash in url to backslash on windows

### ISSUE THREAD

**Issue by kmpm** [mariocasciaro/gulp-concat-css#1]
I have a case where I try to concat a css which have 

``` css
@font-face {
  font-family: 'FontAwesome';
  src: url('../fonts/fontawesome-webfont.eot?v=4.0.3');
  src: url('../fonts/fontawesome-webfont.eot?#iefix&v=4.0.3') format('embedded-opentype'), url('../fonts/fontawesome-webfont.woff?v=4.0.3') format('woff'), url('../fonts/fontawesome-webfont.ttf?v=4.0.3') format('truetype'), url('../fonts/fontawesome-webfont.svg?v=4.0.3#fontawesomeregular') format('svg');
  font-weight: normal;
  font-style: normal;
}
```

which ends up as

``` css
@font-face {
  font-family: 'FontAwesome';
  src: url("font-awesome\fonts\fontawesome-webfont.eot?v=4.0.3");
  src: url("font-awesome\fonts\fontawesome-webfont.eot?#iefix&v=4.0.3") format('embedded-opentype'), url("font-awesome\fonts\fontawesome-webfont.woff?v=4.0.3") format('woff'), url("font-awesome\fonts\fontawesome-webfont.ttf?v=4.0.3") format('truetype'), url("font-awesome\fonts\fontawesome-webfont.svg?v=4.0.3#fontawesomeregular") format('svg');
  font-weight: normal;
  font-style: normal;
}
```

Ok that backslash is normal path divider on windows but it's not allowed in urls and should therefore not ever appear in a css.
This is probably done in a component that culp-concat-css uses but I it's still wrong.
